# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StitchExamples' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StitchExamples
  pod 'StitchSDK', '= 5.0.0'
  pod 'StitchSDK/StitchTwilioService', '= 5.0.0'
  pod 'StitchSDK/StitchAWSService', '= 5.0.0'

  target 'StitchExamplesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StitchExamplesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
